### ISSUE TITLE
Better handling of inaccuracies of ase wrapping

### ISSUE THREAD

**Issue by agoscinski** [cosmo-epfl/librascal#160]
wrapping with ase can sometimes not work because of numerical inaccuracies and the python user is not informed that the wrapping is the problem:
- inside the python `structure_manager.py` the error messages of c++ is catched by python and not forwarded to the python user, remove it or forward the error https://github.com/cosmo-epfl/librascal/blob/ea9be1157437402a54b114d6894cf4f925f85e05/bindings/rascal/neighbourlist/structure_manager.py#L41-L51
- the default tolerance of the wrap functionality of ase is 1e-7, we should stick to the same or a slightly lower accuracy so there are not wrapping errors when using it

**Comment by mastricker** [comment]
That will be part of the ghost PR next week. But I have to add something:

Since we do not impose units on anything e.g. the positions in this case (and `ase` does), I would rather not comply with an external library, but state the tolerance in the error message, if something supposedly wrapped does not pass the runtime check.

Something like: Atoms outside box, calculated with tolerance of 1e-10. Please wrap atoms inside the cell. If you wrapped atoms, check your tolerance.

**Comment by Luthaf** [comment]
> the default tolerance of the wrap functionality of ase is 1e-7, we should stick to the same or a slightly lower accuracy so there are not wrapping errors when using it

I just ran into an error because of this, so :+1: for having a better error message !

**Comment by mastricker** [comment]
This has been addressed in #197 and also in a previous one in that the output now states the used tolerance.
