### ISSUE TITLE
Gradient computation is too slow

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#169]
Just putting this here because we've discussed it in group meetings, but never actually written it down here. I don't remember if we've nailed down exact numbers, but it's something like 10-25x slower for SphericalExpansion gradients than computing the expansion coefficients themselves.

Tasks:

- [ ] benchmark gradient computation for SphExpn. and SphInvts.
- [ ] run profiler (vtune?) to see where most of the time is being spent
- [ ] optimize
- [ ] ...?
- [ ] profit!

If anyone has already run benchmarks on a recent version of the spherical expansions and invariants with their gradients, please post the results here (@agoscinski ?)

**Comment by felixmusil** [comment]
I compared master (573f202d8daea12597e2ad34f65cc71689661aea) with quippy and #228 on the computation of the soap gradients on molecular_crystal.json:
master -> ~0.76 s
#228 -> ~0.62 s
quippy -> 1.7 s

When comparing the timings for the computation of the representation I also find a factor of 3 between us master and quippy. It suggest that gradients are inherently slow to compute I would say. 

So I would say that we can look into it be it is not a high priority since its already not bad right ?

**Comment by Luthaf** [comment]
How many atoms are there in `molecular-crystal.json`? I would like to see the numbers for a very large structure (5000 atoms), a medium one (500 atoms) and a small one (50 atoms) to see if there is any difference here.

**Comment by felixmusil** [comment]
molecular-crystal.json has about 200 atoms.

**Comment by max-veit** [comment]
Ok, I know this is an old issue, but I think we can safely close it now with #293 .
