### ISSUE TITLE
Double free / corruption with DVR

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/librascal#222]
Running the python script below with the latest master gives "corrupted size vs. prev_size" or segfaults on python exit.

```py
#!/usr/bin/env python3
import numpy as np
from ase import Atoms

import rascal
from rascal.representations import SphericalInvariants as SOAP

HYPERS = {
    'soap_type': 'RadialSpectrum',
    'interaction_cutoff': 3.5,
    'max_radial': 15,
    'max_angular': 0,
    'gaussian_sigma_constant': 0.5,
    'gaussian_sigma_type': 'Constant',
    'cutoff_smooth_width': 0.5,
    'radial_basis': 'DVR',
}

h4 = Atoms(
    symbols='H5',
    positions=[(0, 0, 0), (0, 0, 2), (0, 0, -2), (0, 2, 0), (0, -2, 0)],
    cell=[20, 20, 20],
    pbc=True
)
h4.wrap()

soap = SOAP(**HYPERS)
feat = soap.transform(h4)

feat = feat.get_features(soap)
```

Am I doing something wrong or is this a memory error?

**Comment by max-veit** [comment]
I'm not seeing anything blatantly wrong with the parameters or the invocation, so maybe it's a memory error in DVR-SOAP. Can you write out the structure to a JSON file and add the file and hypers to the list of those tested in `MultipleHypersSphericalInvariants`? (It looks like DVR is currently tested only for SphericalExpansion, not SphericalInvariants.)

**Comment by agoscinski** [comment]
I also had some problems on the benchmark side using DVR. I am currently on this bug. Here is the json with which it should also happen
```
{"1": {
 "cell": [[20.0, 0.0, 0.0], [0, 20.0, 0.0], [0.0, 0.0, 20.0]],
 "numbers": [1,1,1,1,1],
 "pbc": [true, true, true],
 "positions": [[0, 0, 0], [0, 0, 2], [0, 0, 2], [0, 2, 0], [0, 2, 0]],
 "unique_id": "217edf259bd3ee9d03f1b1754af9b856",
 "user": "musil"},
"ids": [1],
"nextid": 6}
```

**Comment by felixmusil** [comment]
> (It looks like DVR is currently tested only for SphericalExpansion, not SphericalInvariants.)

to avoid longer test time I did not put dvr in the tests of SphericalInvariants. Also the test seemed a bit redundant.

**Comment by max-veit** [comment]
But @agoscinski is the bug only in SphericalInvariants or also in SphericalExpansion with the structures you show? That would at least tell us where the error is (besides perhaps telling us that testing SphericalInvariants with all the same parameters as SphericalExpansion is not redundant).

**Comment by agoscinski** [comment]
The bug happens in both cases, it happens when max_angular is 0. Is there a test case for DVR with `max_angular=0`?

To be more concrete it is the in bessel function for max angular = 0 (just had a look with @felixmusil )
for `l_max=0` it will be`order_max = -1`
https://github.com/cosmo-epfl/librascal/blob/d9dd3e8721eddc8b014e95bcb2340d1e6134acb6/src/rascal/math/bessel.hh#L82-L83
and then you get here a seg fault
https://github.com/cosmo-epfl/librascal/blob/d9dd3e8721eddc8b014e95bcb2340d1e6134acb6/src/rascal/math/bessel.hh#L154-L161

@felixmusil mentioned he will work an the bessel function so he will fix this.

**Comment by max-veit** [comment]
> The bug happens in both cases, it happens when max_angular is 0. Is there a test case for DVR with `max_angular=0`?
> 
> To be more concrete it is the in bessel function for max angular = 0 (just had a look with @felixmusil )
> for `l_max=0` it will be`order_max = -1`
> 
> https://github.com/cosmo-epfl/librascal/blob/d9dd3e8721eddc8b014e95bcb2340d1e6134acb6/src/rascal/math/bessel.hh#L82-L83

since when is `static_cast<int>(0 + 1) == -1`?

> and then you get here a seg fault
> 
> https://github.com/cosmo-epfl/librascal/blob/d9dd3e8721eddc8b014e95bcb2340d1e6134acb6/src/rascal/math/bessel.hh#L154-L161

Is it because `order` is less than 0 that the indexing of `vals` fails?

**Comment by agoscinski** [comment]
yes exactly. so for the aforementioned case we need to add a test (DVR + `max_angular=0` add to SphExp tests).

The fix is to skip the `downward_recursion` function for this case and to calculate directly 
https://github.com/cosmo-epfl/librascal/blob/d9dd3e8721eddc8b014e95bcb2340d1e6134acb6/src/rascal/math/bessel.hh#L53

**Comment by max-veit** [comment]
Oh, I remember the parameter set for SphericalExpansion with `max_angular=0` got stripped out a while ago in the name of improving test runtime. Whether it's before or after the DVR tests got added I don't remember.
