### ISSUE TITLE
Property access wrong since always

### ISSUE THREAD

**Issue by tjunge** [cosmo-epfl/librascal#244]
All properties made their access with `cluster.get_cluster_index(caller_layer)` instead `cluster.get_cluster_index(property_layer)`.

In only never popped up in the tests, because they always use properties at the same layer where they were created.

Furthermore, we propose to get rid of the `PropertyLayer` template parameter, since it is never used in a situation where the runtime value `get_property_layer()` wouldn't do suffice. The advantage is that we then could dynamic_cast properties.

**Comment by tjunge** [comment]
We couldn't figure out how this works in PropertyBlockSparse. Could one of you Cosmonauts assign themselves and look into this?

**Comment by felixmusil** [comment]
it is done exactly in the same manner as in property_typed: operator[] is overloaded to take ClusterRefKey<Order, CallerLayer> as input and calls get_cluster_index(CallerLayer) to access the proper subset of the data. 
Is the problem that CallerLayer is not the proper argument and it should be computed with get_property_layer() ?

**Comment by mastricker** [comment]
Yes, that is basically it. The property nows _its_ layer. The `CallerLayer` is the wrong argument.

We are working on a solution. The current version is wrong, which can be shown (we are adding a test). It just happens to be right, because we accessing properties only at the specific levels.

Once we are done on our side someone of you could have a look at the `PropertyBlockSparse` - so nothing to be done currently for you, only after.

**Comment by max-veit** [comment]
I don't know... the Layer attribute has always seemed to me like an additional complication that doesn't pull its own weight. Could you please remind me what it is meant to be used for? (And if it was meant to be useful for Spherical* representations, I think the very fact that we always use the same Layer speaks to the redundancy of this attribute for these types of representations, at least)

**Comment by mastricker** [comment]
It very much does pull it's own weight, at least on our side it is indispensable.

Suppose you build up something like this:

StructureManager -> AdaptorNeighbourList -> AdaptorStrict -> AdaptorMaxorder

with the arrows indicating stacking, of course.
The distances of pairs are calculated in AdaptorStrict. And attached to that manager.

The function to retrieve the distances of pairs when iterating like this:
(pseudo code)
```
auto & distances{AdaptorStrict.get_property("distances")}
for (atom : AdaptorMaxOrder)
  for(pairs : atom.pairs())
        dist = distances[pair]
```
Only works, because the clusters (here pairs) carry their _previous_ index, when their distance was calculated.

The access is somewhat similar to
```
    template <size_t Order, size_t Layer>
    double get_distance(const ClusterRefKey<Order, Layer> & pair) const {
      return this->distance->operator[](pair);
    }
```
Same goes for direction vectors. The only way to retrieve the correct distance for that pair is if the property distance knows its layer it was created in and if the cluster carries the respective indices for each layer. And the choice of which index to actually use is the topic of this bug. It is wrong. It always chose the highest layer index.

And it did not pop up until now, because when you are calculating your SOAP, you are iterating over the AdaptorStrict. You never had to iterate over a higher than order 2 manager.

That's why in your specific case it did not matter, but on our side it is indispensable for efficiency.
Another idea would be to implement an atom mask, species list, etc. anything you would want to attach to a cluster in the form of a property.

So in short, the Layer attribute is intended used to access properties from equal or lower layer with equal or higher layer clusters.

E.g. one could think of
StructureManager -> AdaptorNeighList -> AdaptorStrict -> AdaptorMaxOrder -> SpeciesManager --> lots of adaptors sorted by leading species.

At the top of the stack we are 3 layer _above_ the point where the distances were calculated. We don't want to calculate them again.
Same goes for angles which could e.g. be attached to the AdaptorMaxOrder (because that is when triplets exist).

Maybe a look at the [whitepaper](https://cosmo-epfl.github.io/librascal/whitepaper.html) also helps?
The fact that it is not used/needed in the SOAP implementation because a different route for implementation was chosen does not make it redundant.
The soapified Behler descriptors will also need it.

**Comment by max-veit** [comment]
Yes, I've (re)read the whitepaper several times, and still haven't really gotten much out of it regarding the distinction between cluster order (which is the distinction between the "layers" in the example above) and Layer, other than the species filtering example. I thought we'd already taken care of the filtering with the whole centers/ghosts distinction, but maybe you have extra filters (other than species filters) you want to apply to higher-order clusters.

I'm not trying to say that, just because a code feature is unused in the SOAP implementations, it's useless for the library as a whole. What I was trying to say is that it's not a good sign that we haven't been able to make use of this functionality in the Spherical* implementations yet, either because it's not general enough to accommodate an efficient implementation of the species/center filtering we do with SOAPy descriptors, or because it hasn't been seen as ready for use because the Behler-Parinello descriptors aren't merged to master yet. Either way, it's just another sign of the divergence of the two implementations that we need to stem by merging the B-P descriptors as soon as possible.

Finally, I propose the formal name "saponified" be used (instead of "soapified") to refer to the B-P descriptors in a SOAP-style formulation.

**Comment by mastricker** [comment]
I have a couple of points where I see the use of the filtering, but that is beside the point of the discussion here. I suggest postponing this to the meeting tomorrow.
Even if it is just for the distances and direction vectors, it is still useful. Making the access to those Properties painlessly.

And I agree with the (hopefully soon) merge of BP descriptors... maybe that will provide a view on a possible implementation for SOAP, possibly even a more efficient one? I have no idea, we have to see.
We had several discussion about the block sparse property. I don't recall the details, but e.g. adding the block sparse properties on the SOAP side was a choice made to better match how it is written mathematically, which was lacking in librascal, but did not necessarily fit to the initial ideas that Till had when he conceptualized the data structures and envisioned their use. Maybe not all was known at that time.

From the meeting minutes:
>The discussion about the block sparse data structure spurred a further discussion about two different ways of looking at it. LAMMMers solve that problem by attaching the sparse data to dense representations of the underlying iteration (let’s call it iteration view), COSMOers in need a storage format, which allows access to dense blocks, but is abstracted to the user and should have an a scalar product defined on it (e.g. a map<int, array>, where int is some kind of still unspecified key to access the dense chunk)

I am guessing the BP will clear up some of the differences.

Saponified is good. I was just quoting your boss using _soapified_ :)
