### ISSUE TITLE
Using type `X` for atoms yields nonsense SOAP vectors

### ISSUE THREAD

**Issue by rosecers** [cosmo-epfl/librascal#288]
PDF of jupyter notebook:
[issue_with_xtype.pdf](https://github.com/cosmo-epfl/librascal/files/5188756/issue_with_xtype.pdf)

Code for reference:

```python
import ase
from ase import Atoms
print("ase version:", ase.__version__)

import rascal
from rascal.representations import SphericalInvariants as SOAP
print("rascal version:", rascal.__version__)

import matplotlib
from matplotlib import pyplot as plt
print("Matplotlib version:", matplotlib.__version__)

import sys
print("Python version:", sys.version)

hypers = dict(max_radial=12, max_angular=12,
              soap_type="PowerSpectrum",
              gaussian_sigma_type="Constant",
              gaussian_sigma_constant=0.5,
              cutoff_smooth_width=0.5,
              interaction_cutoff=2.0
             )

# simple, non-primitive BCC structure
frameX = Atoms('X2',
                 positions=[[0, 0, 0], [0.5, 0.5, 0.5]],
                 cell=[1, 1, 1],
                 pbc=[1, 1, 1])

soap = SOAP(**hypers)
c = soap.transform(frameX)
rep = c.get_features_by_species(soap)

print('Species keys: ', rep.keys())

for key in rep.keys():
    plt.plot(rep[key][0], label=key)
plt.legend()
plt.show()

# simple, non-primitive BCC structure
frame = Atoms('C2',
                 positions=[[0, 0, 0], [0.5, 0.5, 0.5]],
                 cell=[1, 1, 1],
                 pbc=[1, 1, 1])

soap = SOAP(**hypers)
c = soap.transform(frame)
rep = c.get_features_by_species(soap)

print('Species keys: ', rep.keys())

for key in rep.keys():
    plt.plot(rep[key][0], label=key)
plt.legend()
plt.show()
```

**Comment by rosecers** [comment]
Using type `X`
![image](https://user-images.githubusercontent.com/47536110/92486445-678b9c00-f1ec-11ea-8625-45abc24a5512.png)

Using type `C`
![image](https://user-images.githubusercontent.com/47536110/92486456-6ce8e680-f1ec-11ea-9e8f-ca0dcfb6d12f.png)

**Comment by max-veit** [comment]
Looks like this is due to species 'X' translating into an atomic number of zero, which is probably filtered out somewhere along the line as an "unreasonable" species key (and apparently silently ignored...?). @felixmusil any ideas where this might be happening? And how should we handle cases with unspecified atomic species, just sort them into species 0 and treat that like any other species?

**Comment by Luthaf** [comment]
> And how should we handle cases with unspecified atomic species, just sort them into species 0 and treat that like any other species?

How about assigning them pseudo atomic number as `120 + hash(name)`, where hash produces a 32-bit hash of the name? This allow to support multiple different non-atomic species, while still enabling compatibility with standard atomic species. The use of hash instead of counting how many different non-atomic species have been encountered until now allow to guarantee that a unique number is assigned even across different invocations of librascal. 32-bit hash is required to ensure we don't overflow the 64-bit integer used to store atomic number (or we could deal with overflow manually).

**Comment by felixmusil** [comment]
Yes the current implementation of the spherical invariant is not meant to work with unphysical atom types. So any atomic number that is not between 1 and rascal::MaxChemElements will break the computation of spherical invariants of order 2.

**Comment by Luthaf** [comment]
>  What would be the usecase to support unphysical atoms ?

The typical usecase for them is coarse-grained simulations

**Comment by rosecers** [comment]
> Yes the current implementation of the spherical invariant is not meant to work with unphysical atom types. So any atomic number that is not between 1 and rascal::MaxChemElements will break the computation of spherical invariants of order 2.
> What would be the usecase to support unphysical atoms ?

Also, given that ASE supports non-typed atoms, and librascal is built on ASE-type inputs, we should support non-typed atoms as well. From your description, it should be as easy as changing a 1 to a 0, no?

Another use case is for analyses of molecular geometry, where molecules with similar geometry should be noted as similar, even if their one atom type differs.
