### ISSUE TITLE
Error with structure wrapping with ASE: atoms outside the unit cell - neighbourlist of structures failed

### ISSUE THREAD

**Issue by lgigli** [cosmo-epfl/librascal#310]
[Structure_wrap_bug.xyz.txt](https://github.com/cosmo-epfl/librascal/files/5801119/Structure_wrap_bug.xyz.txt)

In order to compute the SOAP vectors of a given structure (previously saved as a simple .xyz file) in librascal, it is necessary to first load it using ase.io.read and then wrap the structure inside the unit cell. The following code snippet has been used in a practical case:

```py
HYPERS = {
    'soap_type': 'PowerSpectrum',
    'interaction_cutoff': 6,
    'max_radial': 6,
    'max_angular': 4,
    'gaussian_sigma_constant': 0.5,
    'gaussian_sigma_type': 'Constant',
    'cutoff_smooth_width': 0.5,
    'radial_basis': 'GTO',
    'normalize' : False,
    'inversion_symmetry': True,
}
soap = SOAP(**HYPERS)

f = read("Structure_wrap_bug.xyz", format="xyz")
f.wrap(eps=1e-18)
cell = f.get_cell()

feat = soap.transform(f).get_features(soap)
x.append(feat.mean(axis=0))
x = np.asarray(x)
```

For the structure that I report in the attachment, despite the ase wrapping had been successful (because all the atom positions lie inside the unit cell), librascal sent this error message: 

**RuntimeError: Neighbourlist of structures failed because: Error: At least one atom is outside the unit cell. This adaptor expects atoms to be folded into the original unit cell. ccoord = (7, 2, 6), nboxes = (8, 8, 8)**

This error persists even by changing the librascal branch, or even by just using the up-to-date master branch.

**Comment by lgigli** [comment]
[Structure_wrap_bug_spglib.xyz.txt](https://github.com/cosmo-epfl/librascal/files/5802490/Structure_wrap_bug_spglib.xyz.txt)
Sanitization of the cell with the spglib library (standardize_cell method) gives the same issue with the structure that I upload here.

The following is the code snippet that I used: 

f = read("Structure_wrap_bug_spglib.xyz", format="xyz")
lattice, scaled_positions, numbers = standardize_cell(f, to_primitive=False, no_idealize=False, symprec=1e-5)
f.set_cell(lattice)

f.wrap(eps=1e-18)
feat = soap.transform(f).get_features(soap)
x.append(feat.mean(axis=0))
x = np.asarray(x)

**Comment by Luthaf** [comment]
This looks like an issue with the cell list. Looking at the file, I'm wondering whether the issue is that some atoms have negative coordinates after wrapping:

**Comment by sshepherd637** [comment]
Hi all, just to add to the above, this issue is prevalent for a number of different datasets, and occurred when I was using rascal for a range of my datasets. 

I've included an example frame which has produced the error stated above for myself. Again this occurs after wrapping is done on the dataset similarly to that outlined above.

```
from ase.io import read, write

frames = read('frames.xyz', ':')
for i in range(len(frames)):
        frames[i].wrap(1e-15)
```

To add some detail to the previous comment about negative coordinates, this structure is one of many with negative coordinates post wrap. They are generally getting transformed with no issues and it is only the minority that is causing this error. 

[atomlist_error_structure.xyz.txt](https://github.com/cosmo-epfl/librascal/files/6109790/atomlist_error_structure.xyz.txt)

**Comment by ceriottm** [comment]
This is really something we need to fix once and for all.

**Comment by felixmusil** [comment]
> This is really something we need to fix once and for all.

Which course of action do you propose we follow ? @ceriottm

**Comment by max-veit** [comment]
We can try to figure out what's going on in this specific case, for starters, since it seems like the two issues (Lorenzo's and Sam's) are related. These are all structures that ASE considers "wrapped" (the negative coordinates are just because some of the cell vectors have negative components; the atoms are still all inside the cell). But for some reason, these `ccoords` (which I'm guessing are cell indices for the linked-cell algorithm?) are being constructed in a way that gives invalid results for valid structures.

So I'd suggest we look at how the `ccoords` are calculated for a few simple cubic structures, both ones that give the error and ones that don't, and see if there are any features of the structures themselves that can explain the difference. It's been suggested that perhaps this has to do with atoms being right on a cell boundary (since shifting the atoms and re-wrapping fixes the issue in most cases); perhaps we can try to replicate that condition?

But really, I think all these issues are indicating that a deep refactoring of the neighbourlist code is on the horizon. We've had disproportionately many issues arising from this core component, so perhaps it's worth considering redesigning it along the lines of what established codes like QUIP or even ASE already do, without worrying too much about optimizing instruction counts -- we've already seen from our benchmarks that the neighbourlist cost is tiny both in librascal and in QUIP, so there's no excuse for trading stability and maintainability for efficiency here.

**Comment by max-veit** [comment]
Oh, and @sshepherd637 , thanks for describing the issue and providing the structure! Perhaps you could also upload one structure where the neighbourlist computation succeeds, just for comparison? Also, what was the cutoff you chose for the potential? I have a feeling that might be important, especially if we're dealing with an issue involving the linked-cell neighbourlist.

**Comment by sshepherd637** [comment]
Of course, attached is an example of a similar frame post wrapping which didn't cause any problems whatsoever. As for the cutoff, I used 4 Å.

[working_structure.xyz.txt](https://github.com/cosmo-epfl/librascal/files/6110368/working_structure.xyz.txt)
