### ISSUE TITLE
SOAP vectors - error atoms outside unit cell 

### ISSUE THREAD

**Issue by elenagazzarrini** [cosmo-epfl/librascal#338]
I am using librascal to calculate SOAP vectors - works great apart from the fact that, even if I use frames.wrap(eps=1e-12), to wrap ase frames, I continuously get the error that some atoms are outside unit cell.

**Comment by ceriottm** [comment]
Have you updated to the latest version? I thought this had been fixed already about a month ago. Please check and if you still get errors please attach an example of the structures that give errors

**Comment by max-veit** [comment]
Hi, thanks for reporting! This looks like an issue that was fixed in PR #322 ; could you please make sure you're using at least that version and recompile (using `make clean`), then try again?

If the issue persists, we'd appreciate it if you could provide a few more details; see #310 for examples (perhaps we could continue the discussion there if the issue persists).

**Comment by ceriottm** [comment]
@elenagazzarrini  did you solve this problem?

**Comment by elenagazzarrini** [comment]
Yes thanks it works fine now that I updated the repository!
