### ISSUE TITLE
AttributeError: 'rascal.lib._rascal.neighbour_list.Adaptor.Strict_C' object has no attribute 'get_atomic_numbers' in MLIP_example.ipynb

### ISSUE THREAD

**Issue by hezhengda** [cosmo-epfl/librascal#345]
When trying to execute the `MLIP_example.ipynb`

Error message:
![image](https://user-images.githubusercontent.com/26743576/116379953-d0736300-a813-11eb-8315-89343ecfedb0.png)

To my understanding, this is related to the `managers_train` object, which it doesnt have the `get_atomic_numbers()` methods (as you could see in the figure below).

![image](https://user-images.githubusercontent.com/26743576/116379606-770b3400-a813-11eb-8ff8-0370381a5b05.png)

**Comment by max-veit** [comment]
Hello, thanks for reporting this! I think I've seen a similar issue before, and it's due to an update of `train_gap_model()` (defined in `bindings/rascal/models/krr.py`) that was not reflected in the examples. This is (also) fixed in #342, which adds automatic validation to make sure this sort of thing doesn't happen again.

I would suggest you update to the `bugfix/ipi` branch for now (or at least use the notebook version from there), until that PR is merged.

**Comment by hezhengda** [comment]
Thanks for the info. I will try the bugfix/ipi branch.

**Comment by hezhengda** [comment]
The new branch works, thanks so much @max-veit for the answer.

**Comment by max-veit** [comment]
No worries, and do let us know if you find other ways to improve the examples!
