### ISSUE TITLE
cpplint warns about C-style casts but clang-format doesn't fix it

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#356]
Apparently the newest version of [cpplint](https://github.com/cpplint/cpplint) is warning about C-style casts, viz. this line: https://github.com/cosmo-epfl/librascal/blob/43a410c6d7cea3d17852e9c8c6fe332ec46f13df/tests/test_utils_sparsify.cc#L72
which is something `clang-format` doesn't seem to touch -- at least, it doesn't convert them to the Proper C++ Cast format.

To fix the issue, we can change the cast, or we could just fix the `cpplint` version in `requirements.txt` to mitigate future random upstream update lossage.

**Comment by Luthaf** [comment]
>  which is something clang-format doesn't seem to touch -- at least, it doesn't convert them to the Proper C++ Cast format.

Yes, because there is more than one possible mapping, so clang-format does not know which one to pick. I think this should be fixed where needed (hopefully all casts can be written as `static_cast`). 

I'm happy with pinning the version of cpplint on CI, did you include the version with or without this lint about C-style casts?

**Comment by max-veit** [comment]
I pinned the latest version in #357, which does have the warning, and changed the offending line to a `static_cast`.
