### ISSUE TITLE
Make JSON schemas to provide a json serialization of StructureManagers and Calculators

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#65]
Related to #54, but on the JSON end: Write a [JSON schema](https://json-schema.org/specification.html) to specify the format of the JSON data your RepresentationManager can take. Most relevant to us is that you can specify required values, data types (e.g. float), and numeric restrictions (e.g. >= 0).

**Comment by felixmusil** [comment]
I would not make a json schema for the hyperparameters format, a good documentation should suffice. 

Making this possible for serializing entire objects is useful though to be able to dump representations and trained models.
I would leverage the [functionalities](https://github.com/nlohmann/json#arbitrary-types-conversions) of the json library we are using, and since many of our types are only [move constructible](https://github.com/nlohmann/json#how-can-i-use-get-for-non-default-constructiblenon-copyable-types) it won't be as elegant as advertised.
