### ISSUE TITLE
cpplint complains about blank lines that clang-format doesn't remove

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#99]
This is especially frustrating as one cpplint complaint makes all the tests on the CI error out, and you'd hope that `make pretty` would at least get rid of this most stupid class of "errors". But no, blank lines at the beginning of code blocks (specifically classes) aren't removed by clang-format, even though they send cpplint into a tizzy.

More generally, I'd like to argue for removing `make lint` for all but one of the CircleCI targets (or make a target just for linting), because otherwise it's hard to see whether the tests failed due to a genuine error or just a quick-fix formatting non-conformance.

**Comment by ceriottm** [comment]
I presume there is no way to instruct clang-format to remove those lines? Alternatively, can't we change the CPPLINT settings so that those lines are ignored, and then have a make lint-pedantic target for those of us who are irked by those white lines? 
I grew to actually like the fact that the code is consistently and cleanly formatted, and I think that having the circleCI complaint when we don't do make lint before pushing is a small price to pay.

**Comment by mastricker** [comment]
Hi,

I see where this frustration comes from. I will have a look, if that can be integrated into the make pretty.
And I tend to agree with Michele.

One way to circumvent this is to do a local `make lint` and just follow the 2-3 errors it throws. I see that this should be automated, but it did not bother me enough to actually do it.

Again, will have a look if it can be integrated.
